import type { CodeDrill } from "../types";

export const CODE_DRILLS: CodeDrill[] = [
  {
    id: "py-punc-1",
    language: "python",
    category: "punctuation",
    difficulty: 1,
    content: "items = [3, 5, 8, 13]\nprint(items[2])",
  },
  {
    id: "py-punc-2",
    language: "python",
    category: "punctuation",
    difficulty: 2,
    content: "config = {'mode': 'fast', 'retry': 2}",
  },
  {
    id: "py-flow-1",
    language: "python",
    category: "control_flow",
    difficulty: 1,
    content: "for step in range(4):\n    total += step",
  },
  {
    id: "py-flow-2",
    language: "python",
    category: "control_flow",
    difficulty: 2,
    content: "if score >= 90:\n    label = 'high'\nelse:\n    label = 'steady'",
  },
  {
    id: "py-fn-1",
    language: "python",
    category: "functions",
    difficulty: 1,
    content: "def clamp(value, low, high):\n    return max(low, min(value, high))",
  },
  {
    id: "py-fn-2",
    language: "python",
    category: "functions",
    difficulty: 2,
    content: "def slugify(name: str) -> str:\n    return name.lower().replace(' ', '-')",
  },
  {
    id: "py-arr-1",
    language: "python",
    category: "arrays",
    difficulty: 1,
    content: "pairs = [(k, v) for k, v in data.items()]",
  },
  {
    id: "py-str-1",
    language: "python",
    category: "strings",
    difficulty: 1,
    content: "message = f\"{user}: {count} tasks left\"",
  },
  {
    id: "js-punc-1",
    language: "javascript",
    category: "punctuation",
    difficulty: 1,
    content: "const ids = [4, 9, 15, 16];\nconsole.log(ids.at(1));",
  },
  {
    id: "js-punc-2",
    language: "javascript",
    category: "punctuation",
    difficulty: 2,
    content: "const opts = { mode: 'safe', retry: 3, log: true };",
  },
  {
    id: "js-flow-1",
    language: "javascript",
    category: "control_flow",
    difficulty: 1,
    content: "for (let i = 0; i < 5; i += 1) {\n  total += i;\n}",
  },
  {
    id: "js-flow-2",
    language: "javascript",
    category: "control_flow",
    difficulty: 2,
    content: "if (ready && !paused) {\n  runTask();\n} else {\n  queueTask();\n}",
  },
  {
    id: "js-fn-1",
    language: "javascript",
    category: "functions",
    difficulty: 1,
    content:
      "function clamp(value, low, high) {\n  return Math.max(low, Math.min(high, value));\n}",
  },
  {
    id: "js-fn-2",
    language: "javascript",
    category: "functions",
    difficulty: 2,
    content: "const formatTag = (name) => name.trim().toLowerCase().replaceAll(' ', '-');",
  },
  {
    id: "js-arr-1",
    language: "javascript",
    category: "arrays",
    difficulty: 1,
    content: "const unique = [...new Set(items)].sort((a, b) => a - b);",
  },
  {
    id: "js-str-1",
    language: "javascript",
    category: "strings",
    difficulty: 1,
    content: "const label = `${user}: ${tasks.length} open`;",
  },
  {
    id: "c-punc-1",
    language: "c",
    category: "punctuation",
    difficulty: 1,
    content: "int values[] = {2, 4, 6, 8};\nprintf(\"%d\\n\", values[1]);",
  },
  {
    id: "c-punc-2",
    language: "c",
    category: "punctuation",
    difficulty: 2,
    content: "struct Config { int retry; char mode[8]; };",
  },
  {
    id: "c-flow-1",
    language: "c",
    category: "control_flow",
    difficulty: 1,
    content: "for (int i = 0; i < 4; i++) {\n  total += i;\n}",
  },
  {
    id: "c-flow-2",
    language: "c",
    category: "control_flow",
    difficulty: 2,
    content:
      "if (score >= 80) {\n  level = 2;\n} else {\n  level = 1;\n}",
  },
  {
    id: "c-fn-1",
    language: "c",
    category: "functions",
    difficulty: 1,
    content:
      "int clamp(int v, int low, int high) {\n  if (v < low) return low;\n  if (v > high) return high;\n  return v;\n}",
  },
  {
    id: "c-fn-2",
    language: "c",
    category: "functions",
    difficulty: 2,
    content: "size_t len = strlen(name);\nchar *copy = malloc(len + 1);",
  },
  {
    id: "c-arr-1",
    language: "c",
    category: "arrays",
    difficulty: 1,
    content: "char label[16] = \"stable\";\nlabel[0] = 'S';",
  },
  {
    id: "c-str-1",
    language: "c",
    category: "strings",
    difficulty: 2,
    content: "snprintf(buffer, sizeof(buffer), \"%s-%d\", tag, value);",
  },
];
